# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spacectl < Formula
  desc "CLI for KubeSpaces — the open control plane for virtual Kubernetes tenants"
  homepage "https://kubespaces.io"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubespaces-io/kubespaces/releases/download/v0.1.1/spacectl_0.1.1_darwin_amd64.tar.gz"
      sha256 "6cd071f673b9090e5bad28ed63768de95bb736462d085c72fde5f938177801bc"

      define_method(:install) do
        bin.install "spacectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubespaces-io/kubespaces/releases/download/v0.1.1/spacectl_0.1.1_darwin_arm64.tar.gz"
      sha256 "096b538038d9b8815fa9adefd8b3a8c5be91638de755995bbd39568d43e9c8e6"

      define_method(:install) do
        bin.install "spacectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubespaces-io/kubespaces/releases/download/v0.1.1/spacectl_0.1.1_linux_amd64.tar.gz"
      sha256 "a203dbe1682314cbdad66df880653f683b6a37f855462d588e73619ab5ee59ba"
      define_method(:install) do
        bin.install "spacectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubespaces-io/kubespaces/releases/download/v0.1.1/spacectl_0.1.1_linux_arm64.tar.gz"
      sha256 "282ddbbaa20003b7fddebe60914611067ef8df30d1ca21b28cd4cff4b2850ab7"
      define_method(:install) do
        bin.install "spacectl"
      end
    end
  end

  test do
    system "#{bin}/spacectl", "version"
  end
end
